# Generated by Django 4.1.2 on 2022-10-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='cars')),
                ('name', models.CharField(max_length=212)),
                ('stars', models.IntegerField(default=0)),
                ('price', models.PositiveIntegerField()),
                ('doors', models.PositiveIntegerField()),
                ('seats', models.PositiveIntegerField()),
                ('transmission', models.IntegerField(choices=[(0, 'Mechanic'), (1, 'Auto'), (2, 'AI')], default=1)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wyf', models.CharField(max_length=212)),
                ('wyg', models.CharField(max_length=212)),
                ('jurney_d', models.DateField()),
                ('return_d', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.car')),
            ],
        ),
    ]
